export const palavras = [
    "CASAS", "LIVRO", "TORRE", "FALTA", "BOMBA", 
    "TERRA", "TERNO", "ONTEM", "MORTE", "CARRO", 
    "ANDAR", "ALTAR", "GATOS", "CALMA", "ARMAS", 
    "PONTO", "LINHA", "PERTO", "LONGE", "PRETO",
    "VAPOR", "FOCOS", "TRAPO", "LIMPO", "BEIJO", 
    "FUNDO", "RITMO", "VIDAS", "SUSTO", "GRAMA", 
    "CALOR", "LUGAR", "SINAL", "PORTA", "NUVEM", 
    "ROSTO", "VERBO", "REINO", "SORTE", "AMIGO", 
    "FOLHA", "TEMPO", "MUNDO", "VINHO", "NOITE", 
    "BANHO", "CORDA", "GRUTA", "LUCRO", "TARDE", 
    "CAMPO", "PERNA", "PRAIA", "GENTE", "JUSTO", 
    "SONHO", "RUBRO", "CLARO", "BAIXO", "CHEIO", 
    "TRAMA", "FARDO", "REVER", "BANCO", "TRIGO", 
    "FORMA", "VERDE", "DENTE", "TENSO", "RAIVA",
];