/*export const words = [ Array com atualmente 100 palavras
    "CASAS", "LIVRO", "TORRE", "FALTA", "BOMBA", "TERRA", "TERNO", "ONTEM", "MORTE", "CARRO", 
    "ANDAR", "ALTAR", "GATOS", "CALMA", "ARMAS", "PONTO", "LINHA", "PERTO", "LONGE", "PRETO",
    "VAPOR", "FOCOS", "TRAPO", "LIMPO", "BEIJO", "FUNDO", "RITMO", "VIDAS", "SUSTO", "GRAMA", 
    "CALOR", "LUGAR", "SINAL", "PORTA", "NUVEM", "ROSTO", "VERBO", "REINO", "SORTE", "AMIGO", 
    "FOLHA", "TEMPO", "MUNDO", "VINHO", "NOITE", "BANHO", "CORDA", "GRUTA", "LUCRO", "TARDE", 
    "CAMPO", "PERNA", "PRAIA", "GENTE", "JUSTO", "SONHO", "RUBRO", "CLARO", "BAIXO", "CHEIO", 
    "TRAMA", "FARDO", "REVER", "BANCO", "TRIGO", "FORMA", "VERDE", "DENTE", "TENSO", "RAIVA",
    "CASAL", "TECLA", "FELIZ", "GRATO", "TOMBO", "VIRAR", "CINZA", "PONTE", "RISCO", "FALHA", 
    "CERTO", "FREIO", "LENTO", "PLANO", "RURAL", "AREIA", "TINHA", "NORTE", "VAGAS", "METRO", 
    "DADOS", "CARRO", "LOUCA", "RAIOS", "POEMA", "JOGOS", "POMBO", "MARTE", "MACHO", "POLVO"
];*/

export const words: string[] = [
    "CARRO", "CASAS", "PORTA", "PRAIA", "FORMA", "LINHA", "PONTO", "GENTE", "MORTE", "CAMPO",
    "LIVRO", "TARDE", "CLARO", "AMIGO", "DENTE", "VINHO", "NOITE", "BANHO", "FOLHA", "JUSTO",
    "SONHO", "GRAMA", "CALMA", "FUNDO", "SINAL", "NORTE", "VERDE", "REINO", "SORTE", "CERTO",
    "BANCO", "TRIGO", "PLANO", "AREIA", "POLVO", "POMBO", "MACHO", "MARTE", "CINZA", "PONTE",
    "RISCO", "FALHA", "LENTO", "FREIO", "PRETO", "LONGE", "PERTO", "LUGAR", "CALOR", "SUSTO",
    "VIDAS", "BEIJO", "TRAMA", "GATOS", "PEDRA", "VELHO", "JOVEM", "MOVEL", "HOTEL", "IDEIA",
    "INATO", "IGUAL", "JUNTO", "LEGAL", "LEITE", "MANIA", "MISTO", "NAVIO", "NEGRO", "NARIZ",
    "OUVIR", "ONTEM", "OLHAR", "ORDEM", "PRATO", "PESCA", "PASSO", "PULAR", "QUERO", "QUEDA",
    "PODER", "SANTO", "SUBIR", "TEMPO", "TOQUE", "XAMPU", "ZUMBI", "MUNDO", "VERAO", "ROCHA",
    "ROUPA", "CRIME", "GRACA", "TESLA", "FRUTA", "RUINA", "PIADA", "BRISA", "CARMA", "DRAMA",
    "NOTAR", "NOVOS", "TRUPE", "TRAJE", "TEXTO", "AMIGA", "AMADO", "VIRAR", "CALMO", "IDOSO",
    "FEROZ", "RURAL", "BRIGA", "TENHA", "FAROL", "PORTE", "VENHA", "ASSAR", "PENER", "PENTA",
    "PLACA", "NUVEM", "SARAU", "PONHA", "VOLTA", "CARGO", "TRATO", "POMAR", "REGRA", "ARTES",
    "CURTO", "DOIDO", "ROLAR", "VOLTO", "FLUOR", "CARTA", "COVER", "ESTAR", "RUMOR", "BUSCA",
    "POEMA", "CONTO", "CANTO", "SAMBA", "LINDA", "DANCA", "AVISA", "FORTE", "BANDO", "FONTE",
    "LENTE", "SALTO", "QUIAO", "PIANO", "CIVIL", "CELAS", "PASTA", "MORRO", "MENTE", "PERDA",
    "GANHA", "MANGA", "DADOS", "COURO", "CHUVA", "FOICE", "GLOBO", "GOSTO", "TROCA", "UNICO",
    "USADO", "URINA", "URUBU", "VEADO", "VENTO", "VOZES", "VERBO", "VIRAM", "VADIO", "CINTO",
    "TORRE", "FALTA", "BOMBA", "TERRA", "TERNO", "ANDAR", "ALTAR", "ARMAS", "VAPOR", "FOCOS",
    "TRAPO", "LIMPO", "RITMO", "CORDA", "GRUTA", "LUCRO", "PERNA", "RUBRO", "BAIXO", "CHEIO",
    "FARDO", "REVER", "TENSO", "RAIVA", "CASAL", "TECLA", "FELIZ", "GRATO", "TOMBO", "TINHA",
    "VAGAS", "LOUCA", "RAIOS", "JOGOS"
];

