/*export const words = [ Array com atualmente 100 palavras
    "CASAS", "LIVRO", "TORRE", "FALTA", "BOMBA", "TERRA", "TERNO", "ONTEM", "MORTE", "CARRO", 
    "ANDAR", "ALTAR", "GATOS", "CALMA", "ARMAS", "PONTO", "LINHA", "PERTO", "LONGE", "PRETO",
    "VAPOR", "FOCOS", "TRAPO", "LIMPO", "BEIJO", "FUNDO", "RITMO", "VIDAS", "SUSTO", "GRAMA", 
    "CALOR", "LUGAR", "SINAL", "PORTA", "NUVEM", "ROSTO", "VERBO", "REINO", "SORTE", "AMIGO", 
    "FOLHA", "TEMPO", "MUNDO", "VINHO", "NOITE", "BANHO", "CORDA", "GRUTA", "LUCRO", "TARDE", 
    "CAMPO", "PERNA", "PRAIA", "GENTE", "JUSTO", "SONHO", "RUBRO", "CLARO", "BAIXO", "CHEIO", 
    "TRAMA", "FARDO", "REVER", "BANCO", "TRIGO", "FORMA", "VERDE", "DENTE", "TENSO", "RAIVA",
    "CASAL", "TECLA", "FELIZ", "GRATO", "TOMBO", "VIRAR", "CINZA", "PONTE", "RISCO", "FALHA", 
    "CERTO", "FREIO", "LENTO", "PLANO", "RURAL", "AREIA", "TINHA", "NORTE", "VAGAS", "METRO", 
    "DADOS", "CARRO", "LOUCA", "RAIOS", "POEMA", "JOGOS", "POMBO", "MARTE", "MACHO", "POLVO"
];*/

export const words: string[] = [ // Array de 200 palavras
  "CARRO", "CASAS", "PORTA", "PRAIA", "FORMA", "LINHA", "PONTO", "GENTE", "MORTE", "CAMPO",
  "LIVRO", "TARDE", "CLARO", "AMIGO", "DENTE", "VINHO", "NOITE", "BANHO", "FOLHA", "JUSTO",
  "SONHO", "GRAMA", "CALMA", "FUNDO", "SINAL", "NORTE", "VERDE", "REINO", "SORTE", "CERTO",
  "BANCO", "TRIGO", "PLANO", "AREIA", "POLVO", "POMBO", "MACHO", "MARTE", "CINZA", "PONTE",
  "RISCO", "FALHA", "LENTO", "FREIO", "PRETO", "LONGE", "PERTO", "LUGAR", "CALOR", "SUSTO",
  "VIDAS", "BEIJO", "TRAMA", "FOLHA", "GATOS", "PEDRA", "VELHO", "JOVEM", "MOVEL", "REINO",
  "HOTEL", "IDEIA", "INATO", "IGUAL", "JUNTO", "LENTO", "LIVRO", "LEGAL", "LEITE", "MANIA",
  "METRO", "MISTO", "NAVIO", "NEGRO", "NARIZ", "OUVIR", "ONTEM", "OLHAR", "ORDEM", "PRATO",
  "PESCA", "PASSO", "PULAR", "QUERO", "QUEDA", "PODER", "SANTO", "SUBIR", "TEMPO", "TOQUE",
  "XAMPU", "ZUMBI", "MUNDO", "VERAO", "ROCHA", "ROUPA", "CRIME", "GRAÇA", "TESLA", "FRUTA",
  "RUINA", "PIADA", "BRISA", "CARMA", "DRAMA", "NOTAR", "NOVOS", "LINHA", "TRUPE", "TRAJE",
  "PODER", "TEXTO", "AMIGA", "AMADO", "VIRAR", "CALMO", "PEDRA", "IDOSO", "FEROZ", "RURAL",
  "BRIGA", "GRAMA", "TENHA", "FAROL", "PORTE", "ROUPA", "VENHA", "ASSAR", "PENER", "PENTA",
  "PLACA", "NUVEM", "SARAU", "PONHA", "VOLTA", "CARGO", "TRATO", "ASSAR", "POMAR", "AMADO",
  "REGRA", "ARTES", "CURTO", "DOIDO", "ROLAR", "TEXTO", "MUNDO", "VOLTO", "FLUOR", "CALOR", 
  "CARTA", "COVER", "ESTAR", "RUMOR", "BUSCA", "DRAMA", "POEMA", "CONTO", "CANTO", "SAMBA", 
  "LINDA", "DANCA", "AVISA", "FORTE", "BANDO", "FONTE", "LENTE", "SALTO", "QUIAO", "PIANO", 
  "CIVIL", "CELAS", "PASTA", "MORRO", "MENTE", "PERDA", "GANHA", "MANGA", "DADOS", "COURO", 
  "CRIME", "CHUVA", "FOICE", "GLOBO", "GOSTO", "TROCA", "UNICO", "USADO", "URINA", "URUBU", 
  "VEADO", "VENTO", "VOZES", "VERBO", "VIRAM", "VADIO", "TRATO", "CINTO", "SONHO", "METRO"
];

